def on_forever():
    pins.analog_write_pin(AnalogPin.P0, 1023)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 454)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 99)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 660)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 1023)
    basic.pause(500)
    pins.analog_write_pin(AnalogPin.P0, 157)
    basic.pause(500)
basic.forever(on_forever)
